#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

if [ -n "$NEW_RELIC_API_KEY" ]; then
    # Notify New Relic of the deployment
    github_url="https://github.com/mozilla/mrburns/compare/${oldrev:0:10}...${newrev:0:10}"
    git_log=$(git log --oneline ${oldrev}..${newrev})
    curl -H "x-api-key:${NEW_RELIC_API_KEY}" \
        --data "deployment[app_name]=${NEW_RELIC_APP_NAME}" \
        --data-urlencode "deployment[description]=Deployment: ${github_url}" \
        --data-urlencode "deployment[changelog]=${git_log}"\
        --data "deployment[revision]=${newrev}" https://rpm.newrelic.com/deployments.xml
fi
