#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

# delete pyc files
find . -name "*.pyc" -delete

bin/peep.py install -r requirements/mrburns.txt -r requirements/mrburns-server.txt \
                    -r requirements/smithers.txt

python manage.py collectstatic --noinput
python manage.py compress

if [ -n $newrev ]; then
    echo $newrev > static/revision.txt
fi
